services:
  db_postgres_ng:
    image: postgres
    container_name: db_postgres_ng
    restart: always
    ports: 
      - 4000:5432
    env_file:
      - .env.a
    volumes: 
      - pg_ng:/var/lib/postgresql/data

  node_app_ng:
    container_name: NG
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_ng
    env_file:
      - .env.a

volumes:
  pg_ng: